app/app.py
#!/usr/bin/env python
from importlib import import_module
import os
from flask import Flask, render_template, Response
import time
import serial
from views import view

# Raspberry Pi camera module (requires picamera package)
# from camera_pi import Camera

app = Flask(__name__)
app.register_blueprint(view)

if __name__ == '__main__':
    app.run(host='0.0.0.0', threaded=True)

app/views.py
from flask import Blueprint, render_template, session, abort, Response
import time
import serial
import os
from pi_serial import uart_communicate

# import camera driver
if os.environ.get('CAMERA'):
    Camera = import_module('camera_' + os.environ['CAMERA']).Camera
else:
    from camera_pi import Camera

view = Blueprint('view', __name__)

@view.route('/')
def index():
    """Video streaming home page."""
    return render_template('index.html')


def gen(camera):
    """Video streaming generator function."""
    yield b'--frame\r\n'
    while True:
        frame = camera.get_frame()
        yield b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n--frame\r\n'


@view.route('/video_feed')
def video_feed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

@view.route('/blue_on')
def blue_on():
    """Route to turn on the Blue LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    """Instantiate UART module for Raspberry Pi"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LBO"
    uart.send_thru_uart(to_send)
    print("Blue_on")
    return ("nothing")
    #return render_template('index.html')

@view.route('/blue_off')
def blue_off():
    """Route to turn off the Blue LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LBF"
    uart.send_thru_uart(to_send)
    print("Blue_off")
    return ("nothing")
    #return render_template('index.html')

@view.route('/red_on')
def red_on():
    """Route to turn on the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LRO"
    uart.send_thru_uart(to_send)
    print("Red_on")
    return ("nothing")
    #return render_template('index.html')

@view.route('/red_off')
def red_off():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LRF"
    uart.send_thru_uart(to_send)
    print("Red_off")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/orange_on')
def orange_on():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LOO"
    uart.send_thru_uart(to_send)
    print("Orange_on")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/orange_off')
def orange_off():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LOF"
    uart.send_thru_uart(to_send)
    print("Orange_off")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/green_on')
def green_on():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LGO"
    uart.send_thru_uart(to_send)
    print("Green_on")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/green_off')
def green_off():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "LGF"
    uart.send_thru_uart(to_send)
    print("Green_off")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/porta_on')
def porta_on():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "GAO"
    uart.send_thru_uart(to_send)
    print("Porta_on")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/porta_off')
def porta_off():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "GAF"
    uart.send_thru_uart(to_send)
    print("Porta_off")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/portb_on')
def portb_on():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "GBO"
    uart.send_thru_uart(to_send)
    print("Portb_on")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/portb_off')
def portb_off():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "GBF"
    uart.send_thru_uart(to_send)
    print("Portb_off")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/portc_on')
def portc_on():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "GCO"
    uart.send_thru_uart(to_send)
    print("Portc_on")
    return ("nothing")
    #return render_template('index.html')
    
@view.route('/portc_off')
def portc_off():
    """Route to turn off the Red LED. TODO: put functionality as a button onClick method to avoid reloading page"""
    uart = uart_communicate()
    if(uart.ser.isOpen() == False):
        uart.ser.open()
    uart.ser.reset_input_buffer()
    to_send = "GCF"
    uart.send_thru_uart(to_send)
    print("Portc_off")
    return ("nothing")
    #return render_template('index.html')

app/templates/index.html
<!DOCTYPE HTML>
<html>
<head>
	<title>Frontend test</title>
	<meta name="viewport" content="initial-scale=1.0" />

	<style>
		#dmm , #dmm2 {
			display: inline-block;
		}

		#turn {
			width: 188px; height: 188px;
		}
		#turn .top
		{
			transform-origin: 94px 94px;
			-moz-transform-origin: 94px 94px;
			-webkit-transform-origin: 94px 94px;
			width: 188px; height: 188px;
		}
		#turn2
		{
			height: 94px;
			width: 94px;
		}

		#turn2 .top
		{
			height: 94px;
			width: 94px;
		}

		#bottom
		{
			position: fixed;
			height: 30px;

			bottom: 0;
			right: 0;
		}
		#bottom .measure
		{
			margin-right: 50px;
			-webkit-overflow-scrolling: touch;
		}
	</style>
	<!-- <script type="text/javascript" src="{{url_for('static', filename='visir_html5/jquery-2.1.3.min.js')}}"></script> -->
	<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
	<script type="text/javascript" src="{{url_for('static', filename='visir_html5/utils.js')}}"></script>
	<script type="text/javascript" src="{{url_for('static', filename='visir_html5/jquery-turnable.js')}}"></script>
	<script type="text/javascript" src="{{url_for('static', filename='visir_html5/jquery-draggable.js')}}"></script>
	<script type="text/javascript" src="{{url_for('static', filename='visir_html5/jquery-updownbutton.js')}}"></script>

    <script type="text/javascript" id="visirjs" src="{{url_for('static', filename='visir_html5/visir.js')}}"></script>

	<script>

	function init()
	{
		var circuit = '<circuit><circuitlist>W_X A23 DMM_VHI\nW_X F23 DMM_VLO\nR_X A23 F23 10k\nVDC+6V AA\nDMM_2 AA 0\n</circuitlist></circuit>';
		var instrxml = '<multimeter id="1"><dmm_function value="ac current"/><dmm_resolution value="3.5"/><dmm_range value="10"/></multimeter><multimeter id="2"><dmm_function value="dc volts"/><dmm_resolution value="3.5"/><dmm_range value="10"/></multimeter>';
		var dcpower = '<dcpower><dc_outputs><dc_output channel="6V+"><dc_voltage value="5"/><dc_current value="0.5"/></dc_output><dc_output channel="25V+"><dc_voltage value="0"/><dc_current value="0.5"/></dc_output><dc_output channel="25V-"><dc_voltage value="0"/><dc_current value="0.5"/></dc_output></dc_outputs></dcpower>';

		trace("starting up..");

		var transport = new visir.JSTransport(visir.SetWorking);
		transport.onerror = function(err) { alert("Error: " + err); }

		transport.Connect("http://194.47.134.182:8080/measureserver", "fnord");

		var breadboard = new visir.Breadboard(1, $("#breadboard"));

		$("#showlog").click( function() {
			$("#logwindow").css("display", "block");
		});
		$("#hidelog").click( function() {
			$("#logwindow").css("display", "none");
		});
	}
	$( function() {
        visir.Load(init, function() {
            alert("Failed");
        }, "");
    });
</script>
<script type="text/javascript" src="{{url_for('static', filename='visir_html5/serial.js')}}"></script>

</head>
<body>
	<button class="measure">Measure</button><br>
	<button class='test_button' onclick='blue_click(this);'>Blue</button>
	<button class='test_button' onclick='red_click(this);'>Red</button>
	<button class='test_button' onclick='orange_click(this);'>Orange</button>
	<button class='test_button' onclick='green_click(this);'>Green</button>
	<button class='test_button' onclick='porta_click(this);'>PortA</button>
	<button class='test_button' onclick='portb_click(this);'>PortB</button>
	<button class='test_button' onclick='portc_click(this);'>PortC</button>
	<br/>
	<div id="dmm"></div>
	<div id="dmm2"></div>
	<div id="tripledc"></div>
	<div id="breadboard"></div>
	<div id="bottom">
		<button class="measure">Measure</button>
	</div>
	<div>
		Log window:
		<button id="showlog">Show</button>
		<button id="hidelog">Hide</button>
	</div>
	<div>
	<!-- <img src="{{ url_for('view.video_feed') }}" width="500" height="400">  -->
	</div>
	<div id="logwindow" style="border: 1px solid #000000; padding: 2px; height: 500px; width: 800px; overflow: scroll; display:none"></div>
</body>
</html>